version: '3.8'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - agrivest_network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: agrivest
            MYSQL_ROOT_PASSWORD: Local1234
        networks:
            - agrivest_network

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "802:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - agrivest_network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: Local1234
        ports:
            - "803:80"
        depends_on:
            - db
        networks:
            - agrivest_network
    redis:
        image: redis:alpine
        container_name: laravel-redis
        restart: unless-stopped
        networks:
            - agrivest_network
volumes:
    db_data:

networks:
    agrivest_network:
